name: api caller workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: ブランチ名
        required: true
        default: devalop
        type: string

jobs:
  call_other_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call other workflow
        run: |
          res=$(curl \
            -X POST \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/stnda1one/sandbox-public/actions/workflows/environment_workflow.yml/dispatches \
            -d '{"ref":${{ inputs.branch }}, "inputs": { "environment": "sbx_1" } }')
          echo $res
