name: api caller workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: ブランチ名
        required: true
        default: main
        type: string

jobs:
  call_other_workflow:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [sbx_1]
    steps:
      - name: Call other workflow
        id: call-other-workflow
        run: |
          # res=$(curl \
          #  -X POST \
          #  -w '\n%{http_code}' \
          #  -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
          #  -H "Accept: application/vnd.github.v3+json" \
          #  https://api.github.com/repos/stnda1one/sandbox-public/actions/workflows/environment_workflow.yml/dispatches \
          #  -d '{"ref":"${{ inputs.branch }}", "inputs": { "environment": "${{ matrix.environment }}" } }')
          res=$(curl -X POST -w '\n%{http_code}' -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -H "Accept: application/vnd.github.v3+json" -d '{"ref":"${{ inputs.branch }}", "inputs": { "environment": "${{ matrix.environment }}" } }' \
            https://api.github.com/repos/stnda1one/sandbox-public/actions/workflows/environment_workflow.yml/dispatches)
          # echo "::set-output name=value::${res}"
          echo $res
          echo $res
          echo "value=${res}" >> "$GITHUB_OUTPUT"
      - name: Set http_code
        id: set-http_code
        run: |
          http_code=`echo "${{ steps.call-other-workflow.outputs.value }}" | tail -n 1`
          echo "::set-output name=http_code::${http_code}"
          echo "http_code=${http_code}" >> $GITHUB_OUTPUT
      - name: Show response
        run: echo -e '${{ steps.call-other-workflow.outputs.value }}'
      - name: Exit if HTTP status code is NOT 204
        if: ${{ steps.set-http_code.outputs.http_code != '204' }}
        run: |
          echo "${{ steps.call-other-workflow.outputs.value }}"
          exit 1
