name: second level called workflow

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      environment:
        type: environment

jobs:
  job_1:
    uses: ./.github/workflows/called-workflow-2-1.yml
    with:
      target: ${{ inputs.target }}
    secrets: inherit

  job_2:
    uses: ./.github/workflows/called-workflow-2-2.yml
    with:
      target: ${{ inputs.target }}
    secrets: inherit
