name: environment_workflow

on:
  workflow_dispatch:
    inputs:
      env: 
        required: true
        type: environment

env:
  ENV_URL: https://${{ github.event.inputs.environment }}.co.jp

jobs:
  job_sbx_1:
    runs-on: ubuntu-latest
    environment:
      name: sbx_1
      url: https://yahoo.co.jp
    steps:
      - run: echo deploy sbx_1
  
  job_sbx_2:
    runs-on: ubuntu-latest
    environment:
      name: sbx_2
      url: https://google.com
    steps:
      - run: echo deploy sbx_2

  job_sbx_3:
    runs-on: ubuntu-latest
    environment:
      name: sbx_3
      url: https://search.goo.ne.jp
    steps:
      - run: echo deploy sbx_３

  job_sbx_custom:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.env }}
      url: ${{ env.ENV_URL }}
    steps:
      - run: echo deploy sbx custom
