name: sample

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App
        uses: actions/checkout@v2
        with:
          ref: main
          path: ./sandbox-public
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run App
        run: |
          cd ./sandbox-public/go
          go run main.go
