name: top level caller workflow

on:
  workflow_dispatch:

jobs:
  example_matrix:
    strategy:
      matrix:
        target: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]
    uses: ./.github/workflows/called-workflow-1.yml
    with:
      target: ${{ matrix.target }}
    secrets: inherit
