name: top level caller workflow

on:
  workflow_dispatch:
    inputs:
      environment:
          type: environment
          
jobs:
  example_matrix:
    strategy:
      matrix:
        target: [1,2,3,4,5,6,7,8,9,10]
    uses: ./.github/workflows/called-workflow-1.yml
    with:
      target: ${{ matrix.target }}
    secrets: inherit
