name: top level caller workflow

on:
  workflow_dispatch:

jobs:
  example_matrix:
    strategy:
      matrix:
        target: [1, 2, 3, 4]
    uses: ./.github/workflows/called-wokflow-1.yml@main
    with:
      target: ${{ matrix.target }}
    secrets: inherit
